### ISSUE TITLE
I cant Download the QR

### ISSUE THREAD

**Issue by flacohenao** [monospaced/angular-qrcode#25] opened 2015-09-09 20:55 UTC
i got everything ok, but the download propertie just doesnt work.

**Comment by zjkyz8** [comment] 2015-09-13 01:53
I have same issue, did not get solution

**Comment by flacohenao** [comment] 2015-09-13 15:41
you can do what I did as well... 

Look, put a <a href> download button and give it an id, then go to the script and in the part where the script asign the download URL you can pass it trough DOM elements managements and then the image will be downloaded.

**Comment by kodl** [comment] 2015-10-15 08:17
same issue ...
Found that problem is caused by loosing pointer to DOM on this part of code (line 129)
```javascript
if (link) {
          link.className = 'qrcode-link';
          $canvas.wrap(link);
          domElement = link;
        }
```
main problem is on `domElement = link`

Overhead is set it to this way `domElement = element[0].firstChild`

```javascript
if (link) {
          link.className = 'qrcode-link';
          $canvas.wrap(link);
          domElement = element[0].firstChild;
        }
```

**Comment by monospaced** [comment] 2015-10-16 18:56
interesting @kodl, those 2 code examples should be equivalent, and download does works for me here (in chrome) without this fix:

http://monospaced.github.io/angular-qrcode/

do you have any more info on your setup, is it a particular browser you're experiencing this issue in?

**Comment by ll0jj0xx0** [comment] 2015-10-19 05:31
Same issue here. @kodl is right. After $canvas.wrap(link), the 'link' is no longer the same 'link'.
However the demo link works fine for me too.

**Comment by ll0jj0xx0** [comment] 2015-10-19 05:35
Different Angular version? I'm using Angular 1.3.18

**Comment by kodl** [comment] 2015-10-19 07:03
Angular-qrcode is part of my (bigger project) - I didn't tested the plain component separately (yet) .. On project I'm using "angularjs": "~1.3.17" and tested it on Chrome 45.0.2454.101, iPhone Safari and Android Chrome.

When I've debug it I found, that variable domElement contains <a> element with correct href, but it isn't in the DOM - in DOM was cloned <a> element without href. Seems that `$canvas.wrap(link)` create (for some reason) a copy of <a> element and wrap it around canvas, but return original <a> element which is unattached to DOM (classname is set to 'qrcode-link' on both instances).

I'm going to test it on separate project (on the demo code) .. but currently I'm out of time .. :(

**Comment by monospaced** [comment] 2015-10-19 08:34
Thanks everyone :+1: 

My conclusion is that the behaviour of `angular.element.wrap()` changed between Angular 1.2.10 and 1.4.7.

Should be fixed in c8cf21324bc, and new version 6.1.3 released.

**Comment by monospaced** [comment] 2015-10-19 08:43
Actually looking at the comments here and #24, the behaviour of `wrap()` must had changed by Angular 1.3.x.

**Comment by kodl** [comment] 2015-10-19 08:54
:+1: Thank you for quick fix

**Comment by zjkyz8** [comment] 2015-11-30 01:48
Thank very much for fixing it :)

**Comment by monospaced** [comment] 2016-03-29 13:41
fixed

**Closed by monospaced** 2016-03-29 13:41 UTC
